# Generated by Django 3.2.7 on 2022-01-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
