# Generated by Django 3.2.7 on 2022-05-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
