# Generated by Django 3.2.7 on 2022-01-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, null=True)),
                ("stock", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_active",
            new_name="new",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="product",
            name="fullDescription",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="offerEnd",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="saleCount",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="shortDescription",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=40, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.size",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.variation",
            ),
        ),
    ]
