# Generated by Django 3.2.7 on 2022-01-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20220101_2101"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="variation",
        ),
        migrations.AddField(
            model_name="product",
            name="variation",
            field=models.ManyToManyField(to="product.Variation"),
        ),
        migrations.RemoveField(
            model_name="variation",
            name="size",
        ),
        migrations.AddField(
            model_name="variation",
            name="size",
            field=models.ManyToManyField(to="product.Size"),
        ),
    ]
