# Generated by Django 3.2.7 on 2022-01-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('category', '0002_remove_category_description'),
        ("product", "0004_auto_20220102_0938"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='category',
        # ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="category.Category"),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDescription",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="shortDescription",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
