# Generated by Django 3.2.7 on 2022-01-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_auto_20220102_1140"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(to="product.Tags"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="product.Category"),
        ),
    ]
