# Generated by Django 3.2.7 on 2022-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_auto_20220103_0626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="Fashion", max_length=40),
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.RemoveField(
            model_name="product",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.CharField(default="Fashion", max_length=40),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
