# Generated by Django 3.2.7 on 2022-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220104_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.JSONField(null=True),
        ),
    ]
