# Generated by Django 3.2.7 on 2022-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220105_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation',
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(to='product.Variation'),
        ),
    ]
