# Generated by Django 3.2.7 on 2022-02-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_auto_20220105_2025"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
    ]
