# Generated by Django 3.2.7 on 2022-02-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
