# Generated by Django 3.2.7 on 2022-02-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='name',
            field=models.CharField(default='variation name', max_length=40),
        ),
    ]
