# Generated by Django 3.2.7 on 2022-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_auto_20220222_0919"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="stockXXL",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
