# Generated by Django 3.2.7 on 2022-11-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_variation_stockxxl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Size",
        ),
    ]
