# Generated by Django 3.2.7 on 2022-05-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_variation_stockxxl'),
        ('address', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_names',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='color_info',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_info',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_info',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_info',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
