# Generated by Django 3.2.7 on 2022-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderPayTm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpaytm",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
    ]
