# Generated by Django 3.2.7 on 2022-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderPayTm", "0003_orderpaytm_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpaytm",
            name="color_info",
            field=models.CharField(default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="orderpaytm",
            name="quantity_info",
            field=models.CharField(default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="orderpaytm",
            name="size_info",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
