# Generated by Django 3.2.7 on 2022-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderPayTm", "0004_auto_20220129_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpaytm",
            name="status_info",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
