# Generated by Django 3.2.7 on 2022-11-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderPayTm', '0006_orderpaytm_pkarrqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaytm',
            name='color_info',
        ),
        migrations.RemoveField(
            model_name='orderpaytm',
            name='pkarrqty',
        ),
        migrations.RemoveField(
            model_name='orderpaytm',
            name='quantity_info',
        ),
        migrations.RemoveField(
            model_name='orderpaytm',
            name='size_info',
        ),
        migrations.RemoveField(
            model_name='orderpaytm',
            name='status_info',
        ),
    ]
