# Generated by Django 3.2.7 on 2022-11-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderPayTm', '0007_auto_20221113_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaytm',
            name='transaction_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
